# This is a basic workflow that is manually triggered

name: build kernel tapi ad patch ksu paling eror

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: ucip123/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: ucip123/android-kernel-actions@master
      id: build
      env:
        NAME: ucipo12
      with:
        arch: arm64
        compiler: gcc/12
        defconfig: even_defconfig
        image: Image.gz-dtb

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
